/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#E53935",
        "on-primary": "#F5F5F5",
        "primary-container": "#B71C1C",
        "on-primary-container": "#F5F5F5",
        "secondary": "#B71C1C",
        "on-secondary": "#F5F5F5",
        "secondary-container": "#7F0000",
        "on-secondary-container": "#F5F5F5",
        "tertiary": "#A0A0A0",
        "on-tertiary": "#0C0C0C",
        "tertiary-container": "#2D2D2D",
        "on-tertiary-container": "#F5F5F5",
        "background": "#0C0C0C",
        "on-background": "#F5F5F5",
        "surface": "#1A1A1A",
        "on-surface": "#F5F5F5",
        "surface-variant": "#2D2D2D",
        "on-surface-variant": "#A0A0A0",
        "outline": "#424242",
        "outline-variant": "#2D2D2D",
        "surface-container-lowest": "#0C0C0C",
        "surface-container-low": "#121212",
        "surface-container": "#1A1A1A",
        "surface-container-high": "#2D2D2D",
        "surface-container-highest": "#424242",
        "surface-bright": "#424242",
        "surface-dim": "#0C0C0C",
        "surface-tint": "#E53935",
        "error": "#E53935",
        "on-error": "#FFFFFF",
        "error-container": "#7F0000",
        "on-error-container": "#FFDAD6",
        "success": "#4CAF50",
        "warning": "#FF9800",
        "inverse-surface": "#F5F5F5",
        "inverse-on-surface": "#0C0C0C",
        "inverse-primary": "#B71C1C",
        "primary-fixed": "#E53935",
        "on-primary-fixed": "#FFFFFF",
        "primary-fixed-dim": "#B71C1C",
        "on-primary-fixed-variant": "#F5F5F5",
        "secondary-fixed": "#B71C1C",
        "on-secondary-fixed": "#FFFFFF",
        "secondary-fixed-dim": "#7F0000",
        "on-secondary-fixed-variant": "#F5F5F5",
        "tertiary-fixed": "#A0A0A0",
        "on-tertiary-fixed": "#0C0C0C",
        "tertiary-fixed-dim": "#808080",
        "on-tertiary-fixed-variant": "#0C0C0C",
      },
      borderRadius: {
        DEFAULT: "14px",
        lg: "16px",
        xl: "18px",
        full: "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "gutter": "16px",
        "panel-gap": "8px",
        "grid-unit": "4px",
        "margin-desktop": "32px"
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "tactical-data": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "tactical-data": ["14px", { lineHeight: "1.5", letterSpacing: "0.08em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
};
