/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "var(--color-primary)",
        "on-primary": "var(--color-on-primary)",
        "primary-container": "var(--color-primary-container)",
        "on-primary-container": "var(--color-on-primary-container)",
        "secondary": "var(--color-secondary)",
        "on-secondary": "var(--color-on-secondary)",
        "secondary-container": "var(--color-secondary-container)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "tertiary": "var(--color-tertiary)",
        "on-tertiary": "var(--color-on-tertiary)",
        "tertiary-container": "var(--color-tertiary-container)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "background": "var(--color-background)",
        "on-background": "var(--color-on-background)",
        "surface": "var(--color-surface)",
        "on-surface": "var(--color-on-surface)",
        "surface-variant": "var(--color-surface-variant)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "outline": "var(--color-outline)",
        "outline-variant": "var(--color-outline-variant)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-container-low": "var(--color-surface-container-low)",
        "surface-container": "var(--color-surface-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "surface-bright": "var(--color-surface-bright)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-tint": "var(--color-surface-tint)",
        "error": "var(--color-error)",
        "on-error": "var(--color-on-error)",
        "error-container": "var(--color-error-container)",
        "on-error-container": "var(--color-on-error-container)",
        "success": "var(--color-success)",
        "warning": "var(--color-warning)",
        "inverse-surface": "var(--color-on-background)",
        "inverse-on-surface": "var(--color-background)",
        "inverse-primary": "var(--color-primary-container)",
        "primary-fixed": "var(--color-primary)",
        "on-primary-fixed": "var(--color-on-primary)",
        "primary-fixed-dim": "var(--color-primary-container)",
        "on-primary-fixed-variant": "var(--color-on-primary-container)",
        "secondary-fixed": "var(--color-secondary)",
        "on-secondary-fixed": "var(--color-on-secondary)",
        "secondary-fixed-dim": "var(--color-secondary-container)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-container)",
        "tertiary-fixed": "var(--color-tertiary)",
        "on-tertiary-fixed": "var(--color-on-tertiary)",
        "tertiary-fixed-dim": "var(--color-tertiary-container)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-container)",
      },
      borderRadius: {
        DEFAULT: "14px",
        lg: "16px",
        xl: "18px",
        full: "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "gutter": "16px",
        "panel-gap": "8px",
        "grid-unit": "4px",
        "margin-desktop": "32px"
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "tactical-data": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "tactical-data": ["14px", { lineHeight: "1.5", letterSpacing: "0.08em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
};
